Complaintchatbox
Practice-Enterprise2/AD pull request #113
Opened 2023-04-27 15:09 UTC by nghidaide012

merging live chat box into main -> user will be able to chat with employee in real time when employee accept to have a chat with customer when they see it in customer's contact list

2023-04-28 10:34 UTC, ThomasFrans commented
I quickly enabled extra formatting options to remove more newlines since there were quite a few in your PR. I removed them, merged main and formatted so you don't have to do that :slightly_smiling_face:

2023-04-28 11:21 UTC, ThomasFrans requested changes

2023-04-28 11:21 UTC, ThomasFrans commented on database/migrations/2023_04_16_120412_create_messages_table.php
> +            $table->unsignedBigInteger('from_id');
`foreignId()->constrained()`

2023-04-28 11:21 UTC, ThomasFrans commented on database/migrations/2023_04_16_120412_create_messages_table.php
> +        Schema::create('messages', function (Blueprint $table) {
Give this a more descriptive name to make clear these are chatbox messages. There could be different types of messages in the website, so they should all be clearly labeled in the database.

2023-04-28 11:21 UTC, ThomasFrans commented on database/migrations/2023_04_18_153939_contacts.php
> +            $table->unsignedTinyInteger('is_handled')->default(0);
`bool`

2023-04-28 11:21 UTC, ThomasFrans commented on database/migrations/2023_04_18_153939_contacts.php
> +        Schema::create('contacts', function (Blueprint $table) {
What does this table represent? Just asking to make sure the database schema doesn't contain duplicate information.

2023-04-28 11:21 UTC, ThomasFrans commented on database/migrations/2023_04_18_153939_contacts.php
> +            $table->unsignedBigInteger('customer_id');
`foreignId()->constrained()`

2023-04-28 11:21 UTC, ThomasFrans commented on composer.lock
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-04-28 11:21 UTC, ThomasFrans commented on config/app.php
> +        App\Providers\BroadcastServiceProvider::class,
Already on line 162. I think this might extend that class, in which case that one should probably be removed.

2023-04-28 11:21 UTC, ThomasFrans commented on config/app.php
> +        App\Providers\BroadcastServiceProvider::class,
Move under 'Application Service Providers'

2023-04-28 11:21 UTC, ThomasFrans commented on config/broadcasting.php
> +    'default' => 'pusher',
Leave this configurable (`env('BROADCAST_DRIVER', 'pusher')`)

2023-04-28 11:21 UTC, ThomasFrans commented on config/broadcasting.php
> +            'app_id' => 'staging',
Leave this configurable

2023-04-28 11:21 UTC, ThomasFrans commented on config/broadcasting.php
> -                'scheme' => env('PUSHER_SCHEME', 'https'),
Leave this configurable

2023-04-28 11:21 UTC, ThomasFrans commented on config/broadcasting.php
> -                'useTLS' => 'https' === env('PUSHER_SCHEME', 'https'),
Leave this configurable

2023-04-28 11:21 UTC, ThomasFrans commented on config/websockets.php
> +            'encrypted' => false,
Leave this configurable (the ones that make sense to be configurable through a `.env` file)

2023-04-28 11:21 UTC, ThomasFrans commented on app/Providers/AppServiceProvider.php
> +        static::bootstrap_permission('view_complain', 'view complaints from customers and handle complaint');
Better `view_all_complaints` (action-scope-resource)

2023-04-28 11:21 UTC, ThomasFrans commented on app/Models/contact.php
> +        'customer_id',
Id's aren't mass fillable.

2023-04-28 11:21 UTC, ThomasFrans commented on app/Models/contact.php
> +        'shipment_id',
Id's aren't mass fillable.

2023-04-28 11:21 UTC, ThomasFrans commented on app/Models/contact.php
Follow naming conventions

2023-04-28 11:21 UTC, ThomasFrans commented on app/Models/contact.php
> +class contact extends Model
Follow naming conventions

2023-04-28 11:21 UTC, ThomasFrans commented on app/Models/contact.php
> +    use HasFactory;
It doesn't have a factory.

2023-04-28 11:21 UTC, ThomasFrans commented on app/Models/chatBox.php
> +    }
Shouldn't this refer to `Employee::class`?

2023-04-28 11:21 UTC, ThomasFrans commented on app/Models/chatBox.php
> +    }
Shouldn't the database column be called `user_id` if it just refers to any user?

2023-04-28 11:21 UTC, ThomasFrans commented on app/Models/chatBox.php
> +        'employee_id',
Id's aren't mass fillable.

2023-04-28 11:57 UTC, nghidaide012 commented on app/Models/chatBox.php
> +    }
it refer to user that have employee permission to view list of customer complaint, when they click handled button the chat will be create and their user id will be store inside chatbox table

2023-04-28 11:59 UTC, nghidaide012 commented on app/Models/chatBox.php
> +    }
i do this since i also have another function call employee just easy to check them since the chatbox contain customer_id and employee_id

2023-04-28 12:04 UTC, nghidaide012 commented on vite.config.js
> +    },
for some reason it needed for the echo and pusher to run

2023-04-28 12:06 UTC, nghidaide012 commented on resources/js/test.js
just for testing forgot to delete it

2023-04-28 12:06 UTC, nghidaide012 commented on database/migrations/0000_00_00_000000_create_websockets_statistics_entries_table.php
i never touch that it auto created when install websockets

2023-04-28 12:07 UTC, nghidaide012 commented on database/migrations/2023_04_16_120401_create_chat_boxes_table.php
> +            $table->unsignedBigInteger('employee_id');
i declared foreignID below that

2023-04-28 12:07 UTC, nghidaide012 commented on database/migrations/2023_04_16_120412_create_messages_table.php
> +            $table->unsignedBigInteger('from_id');
i declared foreignID below that

2023-04-28 12:09 UTC, nghidaide012 commented on database/migrations/2023_04_18_153939_contacts.php
> +        Schema::create('contacts', function (Blueprint $table) {
contact-us form for customer that will lead to the chat between customer and employee i already check if it exists in the main branch so i name it that way, can change to customercontact

2023-04-28 12:09 UTC, nghidaide012 commented on database/migrations/2023_04_18_153939_contacts.php
> +            $table->unsignedBigInteger('customer_id');
i declared foreignID below that

2023-04-28 13:03 UTC, ThomasFrans commented on vite.config.js
> +    },
Can you link me the page that says this is needed? This is a major change since Vite compiles all the assets. This could cause big problems for everyone else if this is incorrect. I believe that this may be needed, just want to see where this is explained and whether there is maybe a way to configure Pusher instead.

2023-04-28 13:04 UTC, ThomasFrans commented on database/migrations/0000_00_00_000000_create_websockets_statistics_entries_table.php
Recreate this migration and copy the contents from this file. The way it is currently is called could cause problems.

2023-04-28 13:06 UTC, ThomasFrans commented on database/migrations/2023_04_18_153939_contacts.php
> +            $table->unsignedBigInteger('customer_id');
To be 100% sure use foreignId(). It is provided for a reason.

2023-04-28 13:09 UTC, nghidaide012 commented on app/Models/chatBox.php
> +    }
i did it because only the user table define employee role as in database and have roles as employee i dont find any data or account that in employee table so the point to take data from that table make no sense to me since user table has role to define if it a user or employee or admin

2023-04-28 13:12 UTC, nghidaide012 commented on database/migrations/0000_00_00_000000_create_websockets_statistics_entries_table.php
what problems will it cause when it name that way

2023-04-28 13:13 UTC, nghidaide012 commented on database/migrations/2023_04_18_153939_contacts.php
> +            $table->unsignedBigInteger('customer_id');
isnt the one i use also work the sameway as foreignID?

2023-04-29 12:15 UTC, ThomasFrans requested changes
One small change and it can be merged.

2023-04-29 12:15 UTC, ThomasFrans commented on routes/channels.php
> +use App\Models\chatBox;
Doesn't exist

2023-04-29 12:17 UTC, ThomasFrans approved these changes

2023-04-29 12:19 UTC, merged