Employee overview2
Practice-Enterprise2/AD pull request #116
Opened 2023-04-30 18:26 UTC by ParkwayBE

2023-04-30 18:30 UTC, ParkwayBE commented
i need the user_id in the employee model

2023-04-30 19:30 UTC, ThomasFrans commented
You need to merge main into your branch before it can be merged as it has merge conflicts (and please **not with a PR on GitHub**, just merge it locally).

2023-05-04 09:21 UTC, ParkwayBE commented
> You need to merge main into your branch before it can be merged as it has merge conflicts (and please **not with a PR on GitHub**, just merge it locally)
okay i did that.

2023-05-04 16:52 UTC, ThomasFrans commented
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-05-06 11:50 UTC, ParkwayBE commented
> https://github.com/Practice-Enterprise2/AD#pull-request-requirements

i removed the commented out stuff and i removed the css. I also formatted the code.

2023-05-06 12:42 UTC, ThomasFrans commented
You don't have to remove the CSS, only in components/layouts where it can interfere with other parts of the UI.

2023-05-06 12:56 UTC, ThomasFrans requested changes

2023-05-06 12:56 UTC, ThomasFrans commented on app/Models/Employee.php
> +        'user_id',
Not mass fillable

2023-05-06 12:56 UTC, ThomasFrans commented on app/Models/User.php
> +        'address_id',
Not mass fillable

2023-05-06 12:56 UTC, ThomasFrans commented on resources/views/add_employee.blade.php
> -  <x-employees.create />
This was turned into a Blade component so it could also be included on other pages (like in the control panel). If it is a component it becomes much more reusable.

2023-05-06 12:56 UTC, ThomasFrans commented on resources/views/layouts/navigation.blade.php
> +            </x-dropdown>
The navigation is already too full with stuff. Place this somewhere where it makes sense (as Jente discussed last Thursday). Look on the UI/UX flows in the Discord.

2023-05-13 19:21 UTC, ParkwayBE commented
This should be good to go now.

2023-05-15 19:27 UTC, ParkwayBE commented
I changed what you have told me to change. so this should be good now.

2023-05-16 09:14 UTC, ThomasFrans requested changes

2023-05-16 09:14 UTC, ThomasFrans commented on resources/views/components/employees/create.blade.php
> +</style>
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-05-16 09:14 UTC, ThomasFrans commented on routes/web.php
> +        Route::get('/new_employee', 'showAdd')->name('employee.create');
This route used policies to authorize the action. Why is it removed?

2023-05-16 09:37 UTC, ParkwayBE commented on routes/web.php
> +        Route::get('/new_employee', 'showAdd')->name('employee.create');
sorry I dont understand what should be changed here. can you tell me what should be there instead?

2023-05-16 09:41 UTC, ThomasFrans commented on routes/web.php
> +        Route::get('/new_employee', 'showAdd')->name('employee.create');
In the diff it shows that there used to be middleware for authorization.

2023-05-16 10:22 UTC, ThomasFrans approved these changes

2023-05-16 10:22 UTC, merged