Added shipment validations, error display and automatic calculation of expense
Practice-Enterprise2/AD pull request #121
Opened 2023-05-03 17:38 UTC by biomoz

Added validations when creating, updating shipments and creating waypoints. Added error fields in the pages for user to be notified about the validation errors. Created function to automatically calculate expense instead of direct input.

2023-05-04 09:39 UTC, biomoz commented
I also added role implementations for editing and setting stuff on the shipment only for employess

2023-05-04 16:57 UTC, ThomasFrans requested changes

2023-05-04 16:57 UTC, ThomasFrans commented on app/Providers/AppServiceProvider.php
> +        static::bootstrap_permission('view_shipment_edit', 'view shipment edit page');
Not a good permision. Permissions don't *have* to follow the action-scope-resource naming, but it helps with defining good (correct) ones. Permissions aren't linked to the logic of the application. A better one would be `edit_all_shipments` for example.

2023-05-04 18:28 UTC, biomoz commented on app/Providers/AppServiceProvider.php
> +        static::bootstrap_permission('view_shipment_edit', 'view shipment edit page');
got rid of the view_shipment_edit permission and used edit_all_shipments instead.

2023-05-04 18:38 UTC, ThomasFrans requested changes
I'm sorry I missed these in the previous review.

2023-05-04 18:38 UTC, ThomasFrans commented on app/Models/Shipment.php
>      ];
The rules here are meant to represent the hierarchical structure of a `Shipment`. The `name` field for example has to be `user.name` since it is defined in the `user` relation, not directly on the shipment.

2023-05-04 18:38 UTC, ThomasFrans commented on app/Models/Shipment.php
> +    public const VALIDATION_RULE_WEIGHT = ['required', 'numeric'];
The validation rules for the `user` should go on `User` and be included here. You can apparently construct const arrays from other const arrays using array decomposition (see message in the Discord groupschat).

2023-05-04 18:38 UTC, ThomasFrans commented on app/Models/Waypoint.php
> +    public const VALIDATION_RULE_ARRAY = ['required', 'array'];
The validation rules for the `address` should go on `Address` and be included here. You can apparently construct const arrays from other const arrays using array decomposition (see message in the Discord groupschat).

2023-05-04 18:38 UTC, ThomasFrans commented on app/Models/Waypoint.php
>      ];
The rules here are meant to represent the hierarchical structure of a `Shipment`. The `street` field for example has to be `source_address.street` since it is defined in the `source_address` relation, not directly on the shipment.

2023-05-05 11:41 UTC, ThomasFrans approved these changes

2023-05-05 11:42 UTC, merged