Employee contract new
Practice-Enterprise2/AD pull request #123
Opened 2023-05-03 22:03 UTC by ParkwayBE

updated version including all contracts overview

2023-05-04 07:21 UTC, ThomasFrans commented
You've already merged this I think.

2023-05-04 07:24 UTC, ParkwayBE commented
i created this branch with the same name then the last one. this needs to be merged since there are new changes.

2023-05-08 09:22 UTC, ThomasFrans approved these changes

2023-05-10 13:16 UTC, ThomasFrans commented
I think I marked this as approved but forgot to actually merge it. I'm very sorry if that's the case :/ It's hard to keep up with all the PRs sometimes.

2023-05-18 12:13 UTC, ParkwayBE commented
Updated version I consider this feature done.

2023-05-18 15:23 UTC, ThomasFrans approved these changes

2023-05-18 15:25 UTC, ThomasFrans commented
Still needs to be formatted before it can be merged.

2023-05-18 15:26 UTC, ParkwayBE commented
yes im working on 1 last thing that came to mind. will format after.

2023-05-20 19:47 UTC, ParkwayBE commented
I should have another column in 'employee_contracts' table to save the salary per contract. I created a discord thread in the right channel. For now the contract gets the salary from the 'employees' table. But that one is static. So we should update that one so it changes its value when the contract expires and a new one goes in with a different salary. I noticed other people like Mantriq are using this value of the salary column in 'employees_contract' so we cant just removed it and put it somewhere else. @ThomasFrans

2023-05-21 10:19 UTC, ParkwayBE commented
this should be ready to merge now?

2023-05-21 11:14 UTC, ThomasFrans commented
> this should be ready to merge now?

There are merge conflicts.

2023-05-21 11:21 UTC, ParkwayBE commented
> > this should be ready to merge now?
> 
> There are merge conflicts.
should I resolve these? or?

2023-05-21 11:29 UTC, ThomasFrans commented
Yes

2023-05-21 15:19 UTC, ParkwayBE commented
There are things that are broken now.. trying to fix this

2023-05-21 15:42 UTC, ParkwayBE commented
> > this should be ready to merge now?
> 
> There are merge conflicts.

I fixed them

2023-05-21 16:38 UTC, ThomasFrans requested changes

2023-05-21 16:38 UTC, ThomasFrans commented on routes/web.php
> +        Route::post('/employee_view_contracts/pdf', 'createEmployeeContractPDF')->name('employee-download-contract')->middleware('permission:add_employee');
The permissions aren't correct.

2023-05-21 16:48 UTC, ParkwayBE commented
changed those permission and added a new permission to app service provider for changing contracts

2023-05-21 17:09 UTC, ThomasFrans approved these changes

2023-05-21 17:09 UTC, merged