mergemain
Practice-Enterprise2/AD pull request #125
Opened 2023-05-04 09:46 UTC by nielsver

2023-05-04 16:41 UTC, ThomasFrans commented
Dit is dezelfde PR als de andere die open staat...

2023-05-04 16:47 UTC, ThomasFrans commented
Sluit de andere PR dan aub.

2023-05-04 17:05 UTC, ThomasFrans commented
What does `view_all_overview` grant? I don't quite understand what the permission is used for.

2023-05-05 07:00 UTC, nielsver commented
> What does `view_all_overview` grant? I don't quite understand what the permission is used for.

this is used that only the people with the role management can view the graphs page

2023-05-05 11:51 UTC, ThomasFrans commented
With permissions it's very important not to have a link between permissions and the application logic. Being able to see graphs could require people to have permission to see all employee data, all contract data and all shipment data (this is just an example). The permissions need to be separate and then the logic that checks for permission needs to check these separate ones.

2023-05-08 09:15 UTC, ThomasFrans requested changes
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-05-08 09:15 UTC, ThomasFrans commented on app/Providers/AppServiceProvider.php
> +        static::bootstrap_permission('view_employee_graph', 'view an overview page with graphs of the amount of employees in the company');
This is linked to application logic, which isn't correct. It should be a permission to view the data displayed by the graphs, not a permission to see the graphs themselves. If the graphs show the total amount of employees for example, it could be a permission `view_all_employees` or more specific like `view_employee_count`.

2023-05-09 13:58 UTC, ThomasFrans commented
Not everything has been fixed yet. There is one unresolved issue and also check these again https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-05-09 14:09 UTC, nielsver commented on resources/views/layouts/navigation.blade.php
this is another end user this will only be displayed as that certain user so this shouldn't clutter. it is in the ui/ux flow but they haven't been updated yet we discussed this last week I just asked her to update it again so you can see.

2023-05-09 14:38 UTC, ThomasFrans commented on resources/views/layouts/navigation.blade.php
I just asked and nothing changed since last Thursday. Everything except for 'home', 'dashboard', 'employee', 'control-panel' needs to go somewhere else.

2023-05-09 15:57 UTC, nielsver commented on resources/views/layouts/navigation.blade.php
retalked to jente

2023-05-10 18:23 UTC, ThomasFrans requested changes

2023-05-10 18:23 UTC, ThomasFrans commented on composer.lock
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-05-11 09:30 UTC, ThomasFrans approved these changes

2023-05-11 09:31 UTC, merged