example-commit
Practice-Enterprise2/AD pull request #132
Opened 2023-05-08 15:16 UTC by inancalp

2023-05-08 19:38 UTC, ThomasFrans commented
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-05-09 15:50 UTC, ThomasFrans requested changes

2023-05-09 15:50 UTC, ThomasFrans commented on resources/views/shipments/set.blade.php
>  </script>
This script is incorrectly placed. It will work, but only because browsers are trying to interpret it somehow. Scripts should go between the `<body>` tag (so inside the `<x-app-layout>`).

2023-05-09 15:50 UTC, ThomasFrans commented on app/Http/Controllers/WaypointController.php
> -        );
No validations anymore?

2023-05-09 15:54 UTC, inancalp commented on resources/views/shipments/set.blade.php
> +      // $('.waypoint-select').prop('disabled', true);
It's necessary code that i will be working on

2023-05-09 16:01 UTC, inancalp commented on app/Http/Controllers/WaypointController.php
> -        );
Addresses are fetched directly from DB now.

2023-05-09 16:02 UTC, inancalp commented on app/Http/Controllers/WaypointController.php
> +                dd('waypoint with id: '.$current_waypoint->id." state changed to: 'received'");
remove what?

2023-05-09 16:36 UTC, ThomasFrans commented on resources/views/shipments/set.blade.php
> +      // $('.waypoint-select').prop('disabled', true);
It should be on a new branch then, not as a backup upstream.

2023-05-09 16:38 UTC, ThomasFrans commented on app/Http/Controllers/WaypointController.php
> +                dd('waypoint with id: '.$current_waypoint->id." state changed to: 'received'");
Isn't dd just for debugging?

2023-05-09 17:47 UTC, ThomasFrans commented on app/Http/Controllers/WaypointController.php
> +                // }
I saw you removed the other one but forgot this one. Can you remove this one as well?

2023-05-09 18:23 UTC, inancalp commented on app/Http/Controllers/WaypointController.php
> +                // }
done

2023-05-09 19:11 UTC, merged