Invoicelist 2
Practice-Enterprise2/AD pull request #163
Opened 2023-05-19 12:35 UTC by ParkwayBE

2023-05-20 09:31 UTC, ThomasFrans requested changes

2023-05-20 09:31 UTC, ThomasFrans commented on app/Http/Controllers/InvoiceList.php
Remove this file if it isn't used.

2023-05-20 09:31 UTC, ThomasFrans commented on app/Http/Controllers/InvoicesController.php
> +            $message->to('r0890051@student.thomasmore.be', $data['user']->name.' '.$data['user']->last_name)->subject('Invoice to be paid');
Remove your personal email and create a user with your email instead. Otherwise it will probably stay like this until the demo.

2023-05-20 09:31 UTC, ThomasFrans commented on app/Http/Controllers/InvoicesController.php
> +        return redirect('/invoices_list')->with('success', 'email sent!');
`redirect()->route('<route-name>')` is better because it isn't affected by URL changes.

2023-05-20 09:31 UTC, ThomasFrans commented on routes/web.php
> +        Route::get('/invoices_list/details/mail', 'invoiceMail')->name('invoice-mail')->middleware('permission:view_general_employee_content');
The permissions are completely wrong. `view_general_employee_content` is almost never the correct permission to use. If needed, you should add new ones to `AppServiceProvider`.

2023-05-20 17:50 UTC, ParkwayBE commented
all requested changes should be fixed.

2023-05-22 21:48 UTC, ParkwayBE commented
Fixed all issues and fixed merge conflicts

2023-05-23 11:13 UTC, ThomasFrans approved these changes

2023-05-23 11:13 UTC, merged