fixes for index and show pages and waypoint qr notification
Practice-Enterprise2/AD pull request #177
Opened 2023-05-23 19:30 UTC by biomoz

Index page is only showing the user's shipment now. For employee and admin they can see every shipment.
In show (details) page users are not able to see the qr code anymore. 
On WaypointController I deleted the part for dd (debug) and duplicate code for notification because it was blocking the sending of the notification.

2023-05-23 19:33 UTC, biomoz commented
Btw after the update in the web routes that added "can" functionality, you are not able to see the confirmed shipments as customer. I don't know why we need permissions to see confirmed shipments (also details) anyway but we have to fix it before demo.

2023-05-23 20:53 UTC, ThomasFrans commented
> Btw after the update in the web routes that added "can" functionality, you are not able to see the confirmed shipments as customer. I don't know why we need permissions to see confirmed shipments (also details) anyway but we have to fix it before demo.

It's probably a mistake. You can create a small PR to fix it.

2023-05-23 20:56 UTC, ThomasFrans requested changes

2023-05-23 20:56 UTC, ThomasFrans commented on app/Http/Controllers/ShipmentController.php
> +        if (auth()->user()->hasRole('admin') || auth()->user()->hasRole('employee')) {
Never test for roles directly. There are very, very few cases where testing for a role is correct. Use permissions instead.

2023-05-24 12:35 UTC, biomoz commented on app/Http/Controllers/ShipmentController.php
> +        if (auth()->user()->hasRole('admin') || auth()->user()->hasRole('employee')) {
I have made changes and now i use view_all_shipments permission instead of roles.

2023-05-24 12:46 UTC, biomoz commented
i got rid of the permission check when going into confirmed shipments since everyone should be able to go into that page

2023-05-24 14:03 UTC, ThomasFrans submitted a review, later dismissed

2023-05-24 14:11 UTC, ThomasFrans approved these changes

2023-05-24 14:11 UTC, merged