added migration file for creating user table
Practice-Enterprise2/AD pull request #22
Opened 2023-03-23 10:34 UTC by biomoz

2023-03-29 13:47 UTC, ThomasFrans requested changes
There are a few places that should probably be changed to adhere to the current project conventions.

2023-03-29 13:47 UTC, ThomasFrans commented on app/Models/order.php
> +class order extends Model
Model names should start with an uppercase letter.

2023-03-29 13:47 UTC, ThomasFrans commented on app/Models/order.php
The file name should be `Order.php` like the other models.

2023-03-29 13:47 UTC, ThomasFrans commented on database/migrations/2023_02_16_095555_create_orders_table.php
> +        Schema::create('orders', function (Blueprint $table) {
It would probably be best if all the tables followed the same naming conventions, so snake_case for table fields.

2023-03-29 13:47 UTC, ThomasFrans commented on app/Models/Shipment.php
> +    protected $casts = [
I don't think this is needed for all the fields, only for those where Laravel can't infer the type from the SQL type.

2023-03-30 08:31 UTC, biomoz commented
All the changes you wanted are done. I want to make a new pull request for you to take a look at them

2023-03-30 10:56 UTC, ThomasFrans commented
I don't think you merged correctly with main. You essentially duplicated all code that got merged. When merge conflicts happen, you have to carefully consider the code between the `<<<<<<<<` and `>>>>>>>>` to make sure you combine them correctly. For example look in `routes/web.php`, many routes now appear twice. You should probably revert/reset and retry to merge main into your branch, carefully checking changes.

2023-04-10 19:44 UTC, ThomasFrans commented
There is no point in merging main if you're not going to merge correctly. It's wasted work as this branch cannot be merged, as it will break main in its current state.

2023-04-11 20:28 UTC, biomoz commented
I don't know what conflicts I have to solve to merge with main correctly. Is there any way to view the conflicts that I have now? If I remember correctly, I mostly accepted the incoming changes and sometimes I used both (incoming and current changes). When I merge with main now, it says that there's no conflict but I'm not sure.

2023-04-11 21:01 UTC, ThomasFrans commented
I think it will be pretty hard to correctly merge with main now as I've just formatted the code. I was hesitant to format as there are so many open branches, but formatting (really, **really**) had to happen at some point. The best approach would either be to reapply your changes manually onto the main branch, or to try and merge and pay close attention to resolve any merge conflicts correctly.

2023-04-14 22:05 UTC, closed without merging