Administration customers
Practice-Enterprise2/AD pull request #34
Opened 2023-03-30 09:06 UTC by jentevs

pull request merge

2023-03-30 11:20 UTC, ThomasFrans requested changes
Looks good. There are some minor changes that should probably be made before it's merged.

2023-03-30 11:20 UTC, ThomasFrans commented on routes/web.php
> +
I'm not sure but shouldn't this go into the `auth` and `verified` middleware group above, as well as have a requirement for the admin role? With this route, it seems like anyone could lock/unlock a user, even guests.

2023-03-30 11:20 UTC, ThomasFrans commented on resources/views/admin/users.blade.php
> +                                <td class="px-4 py-2">
Could it be that you forgot a `th` for this column?

2023-03-30 11:20 UTC, ThomasFrans commented on app/Http/Kernel.php
> +        'LockUserAccount' => \App\Http\Middleware\LockUserAccount::class,
Maybe it could be an idea to rename this to `unlocked`, as `LockUserAccount` sounds like this middleware will lock the user account of anyone calling a route with it attached.

2023-03-30 11:20 UTC, ThomasFrans commented on app/Http/Kernel.php
> +        'guest' => [
Could it be that this isn't used at the moment? I don't see any routes using it.

2023-03-30 11:20 UTC, ThomasFrans commented on app/Http/Kernel.php
> +        'guest' => [
What is this used for exactly? Shouldn't the middleware that tests whether an account is unlocked be applied to authenticated routes?

2023-03-30 11:20 UTC, ThomasFrans commented on resources/views/admin/users.blade.php
> +                method: 'POST',
Shouldn't this be a PUT request?

2023-04-04 13:00 UTC, jentevs commented on resources/views/admin/users.blade.php
> +</script>
Thanks for your comment. I am using a POST request to toggle the 'locked' state of a user. The endpoint I'm using is designed to create a new 'locked' state for the user, so a POST request is a suitable choice. A PUT request would be used if I was updating the user's entire object, but that's not what I'm doing here.

2023-04-04 13:07 UTC, ThomasFrans approved these changes

2023-04-04 13:11 UTC, merged