Shipments waypoints
Practice-Enterprise2/AD pull request #44
Opened 2023-04-08 10:50 UTC by inancalp

Changes on Shipment Table.

Waypoint Model/Migration added.

DatabaseSeeder => Shipment and Address Factories commented out.

Shipment Model => source and destination address relations fixed.

Big Update table => shipments->dropColumn 'name' commented out.
resouces/css/app.css => commented out.

QR Code implementation
https://techvblogs.com/blog/generate-qr-code-laravel-8

jQuery added to app.blade.php

Tailwind Form Container added.

Shipments releated link placed on Navigation Bar with a dropdown list.

2023-04-08 15:22 UTC, ThomasFrans requested changes
There are a few remarks I had from quickly going through it (just want to make sure it doesn't break the upstream main branch :wink:) I was wondering if @jentevs can maybe have a look at the changes to the schema in `database/*` as she also worked on the new schema before the break.

2023-04-08 15:22 UTC, ThomasFrans commented on database/migrations/2023_03_01_145506_create_shipments_table.php
Don't edit migrations. Add new ones.

2023-04-08 15:22 UTC, ThomasFrans commented on database/migrations/2023_04_07_145414_create_waypoints_table.php
> +            $table->string('status')->default('In Transit'); // 'In Transit', 'Out For Delivery', 'Delivered', 'Exception'
`set` instead of `string`, then you don't need the commend and everything is checked by the database.

2023-04-08 15:22 UTC, ThomasFrans commented on database/migrations/2023_04_07_145414_create_waypoints_table.php
> +            $table->foreignId('shipment_id');
Add `constrained()`.

2023-04-08 15:22 UTC, ThomasFrans commented on database/migrations/2023_04_07_145414_create_waypoints_table.php
> +            $table->string('current_address_id');
Why not `foreignId()`?

2023-04-08 15:22 UTC, ThomasFrans commented on database/migrations/2023_04_07_145414_create_waypoints_table.php
> +            $table->string('next_address_id');
Why not `foreignId()`?

2023-04-08 15:22 UTC, ThomasFrans commented on database/seeders/DatabaseSeeder.php
> +        // Address::factory()
Why does this have to go?

2023-04-08 15:22 UTC, ThomasFrans commented on database/seeders/DatabaseSeeder.php
> +        // Shipment::factory()
Why does this have to go?

2023-04-08 15:22 UTC, ThomasFrans commented on routes/web.php
> +Route::middleware('auth')->group(function () {
This could be moved up inside the other middleware group just above, not that it matters that much :slightly_smiling_face:

2023-04-09 09:53 UTC, inancalp commented on database/migrations/2023_04_01_100723_big_update.php
> -            $table->dropColumn('name');
No idea. Since it's not relevant, I deleted it from the shipments table itself and then commented out this one. Otherwise it is giving an error that it can't find the "name" attribute to drop.

2023-04-09 09:56 UTC, inancalp commented on database/migrations/2023_03_22_151137_update_shipments_table.php
> -            $table->foreignId('user_id');
"sender_id" is more relevant in case of, shipment is sent by someone. I have directly add the "sender_id" to "create_shipments" table itself. Using "update_tableName" is not necessary for small tables such as shipment_table. It only creates redundancy in the logic and makes the system more complex for others to understand. I would say putting a comment for what is being done is more reasonable.

2023-04-09 09:57 UTC, inancalp commented on database/migrations/2023_03_22_151137_update_shipments_table.php
It's not my migration. I prefer to keep it simple.

2023-04-09 09:57 UTC, inancalp commented on database/migrations/2023_03_01_145506_create_shipments_table.php
#

2023-04-09 09:58 UTC, inancalp commented on database/migrations/2023_04_07_145414_create_waypoints_table.php
> +            $table->string('current_address_id');
It is already foreignId().

2023-04-09 10:01 UTC, inancalp commented on database/seeders/DatabaseSeeder.php
> +        // Address::factory()
It doesn't need to go, but needs a re-implementation. I assume we don't need random addresses at the moment in this way. We can hardcode some addresses for certain scenerios maybe? Including, Our company branch addresses, customer addresses, airport addresses etc... But having random addresses all over the world it not relevant.

2023-04-09 10:03 UTC, inancalp commented on database/seeders/DatabaseSeeder.php
> +        // Shipment::factory()
It does not work with the Shipment Logic I have implemented, and yet no-one seem to use it in any way as I have seen. It needs a re-implementation.

2023-04-09 10:03 UTC, inancalp commented on routes/web.php
> +Route::middleware('auth')->group(function () {
Just wanted to be explicit on the progress I have made, we can get it all together at the end for sure.

2023-04-09 10:06 UTC, inancalp commented on database/migrations/2023_04_07_145414_create_waypoints_table.php
> +            $table->string('current_address_id');
Oh if you mean, current_address_id, you are right. But it's an easy fix just type needs to be changed.

2023-04-09 13:16 UTC, ThomasFrans requested changes
The migrations aren't completely correct yet. If you can fix the final comments, I can merge it.

2023-04-09 13:16 UTC, ThomasFrans commented on database/migrations/2023_04_09_113350_modify_shipments_table.php
> +            ])->nullable();
Why is this nullable? Shouldn't a shipment always be in a certain state?

2023-04-09 13:16 UTC, ThomasFrans commented on routes/web.php
> +Route::middleware('auth')->group(function () {
It's best to be consistent so the code stays clean.

2023-04-09 13:16 UTC, ThomasFrans commented on app/Models/Shipment.php
> +        return $this->hasOne(Address::class, 'id', 'source_address_id');
Why change these to hasOne? I thought when the model holds the foreign id, it should link to the parent using BelongsTo? This change might break other people's code...

2023-04-09 13:26 UTC, inancalp commented on app/Models/Shipment.php
> +        return $this->hasOne(Address::class, 'id', 'source_address_id');
Since the shipment does not belong to a source address, hasOne makes more sense. 'id' (id of Address) and 'source_address_id' (shipment model attribute) is explicitly defined so It won't create any problems as long as attribute names stay same.

2023-04-09 13:27 UTC, inancalp commented on database/migrations/2023_04_09_113350_modify_shipments_table.php
> +            ])->nullable();
That's correct, nullable() is not necessary will delete it.

2023-04-09 13:27 UTC, inancalp commented on database/migrations/2023_04_09_113350_modify_shipments_table.php
> +            ])->nullable();
Forgot it there.

2023-04-09 15:21 UTC, ThomasFrans submitted a review, later dismissed

2023-04-09 15:26 UTC, merged