Shipment notification
Practice-Enterprise2/AD pull request #58
Opened 2023-04-14 21:44 UTC by biomoz

ShipmentController: Added show, edit and delete function for shipments.
Shipment Model: Fixed an error. (HasOne should be HasMany.)
Notifications: Added notification table to database and added a dropdown menu for it in the navigation bar. (When there is an update on the shipment the user that created the shipment will receive a notification.)
Shipment Pages: Updated the pages (index, set, requests pages) for them to look cleaner and added show page to fully show details of shipment. Also added edit page to edit the shipment.
Route: Updated route to be able to function with added pages and features.

Let me know if there are any problems with the PR.

2023-04-14 22:28 UTC, ThomasFrans commented
Can you just format it. It makes it easier to read and merge 🙂 I'll merge it on Sunday.

2023-04-15 12:16 UTC, biomoz commented
I formatted with Laravel pint with ./vendor/bin/pint command. 3 files had changes but no issues on functionality after changes. Everything is working. Hopefully it's fine now. Let me know if there's anything else.

2023-04-15 13:16 UTC, ThomasFrans commented
`php artisan format`

2023-04-15 13:47 UTC, biomoz commented
php artisan format doesn't seem to work: 

PS C:\xampp\htdocs\AD> php artisan format

   Symfony\Component\Process\Exception\RuntimeException 

  TTY mode is not supported on Windows platform.

  at vendor\symfony\process\Process.php:1017
    1013▕      */
    1014▕     public function setTty(bool $tty): static
    1015▕     {
    1016▕         if ('\\' === \DIRECTORY_SEPARATOR && $tty) {
  ➜ 1017▕             throw new RuntimeException('TTY mode is not supported on Windows platform.');
    1019▕
    1020▕         if ($tty && !self::isTtySupported()) {
    1021▕             throw new RuntimeException('TTY mode requires /dev/tty to be read/writable.');      

  1   app\Console\Commands\FormatCode.php:41

  2   app\Console\Commands\FormatCode.php:29
      App\Console\Commands\FormatCode::format_php_code()

Are you sure it's in the main? And also are you using Linux?

2023-04-15 19:52 UTC, ThomasFrans commented
The command is now fixed upstream. If you merge main, you can run it.

2023-04-15 20:57 UTC, biomoz commented
I have done it. Now everything should be fine.

2023-04-16 09:41 UTC, ThomasFrans requested changes
There's one stylistic things I would change to keep the code clean for everyone.

2023-04-16 09:41 UTC, ThomasFrans commented on routes/web.php
> +    });
Move into the middleware group above and remove the individual middleware.

2023-04-16 10:42 UTC, biomoz commented
Deleted the middleware part from the page routes as you asked. Also added mark all as read function to the navigation bar.

2023-04-16 10:44 UTC, biomoz commented on routes/web.php
> +    });
I deleted the middleware parts from the routes since they are not really necessary I think.

2023-04-16 10:44 UTC, ThomasFrans approved these changes

2023-04-16 10:45 UTC, merged