Shipment tracking
Practice-Enterprise2/AD pull request #59
Opened 2023-04-15 09:35 UTC by GillesWS

2023-04-15 13:20 UTC, ThomasFrans commented
Format please.

2023-04-27 11:11 UTC, ThomasFrans commented
Could you just merge main and format again. I added a formatting fix last week which is pretty important (not having it is causing a lot of functions to now be incorrectly indented again, making reviewing this way harder). The commit with that fix isn't on your branch yet.

2023-04-27 11:45 UTC, GillesWS commented
Like this?

2023-04-27 14:22 UTC, ThomasFrans requested changes

2023-04-27 14:22 UTC, ThomasFrans commented on package-lock.json
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-04-27 14:22 UTC, ThomasFrans commented on resources/css/app.css
> +}
I don't really know where these are used but this is a bad idea as literally everyone will get these in their page like this. This change affects every page of our website. Don't add styles here except as sane overrides (like the one below).

2023-04-27 14:22 UTC, ThomasFrans commented on resources/js/app.js
> +//import * as te from 'tw-elements';
Why is this removed? Just like with the styles, people probably depend on this. If this is wrong, it should be removed of course, but I don't know if it is wrong.

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/graphs.blade.php
> +      labels: <?php echo json_encode($day); ?>,
This is the same problem as with the other raw PHP tags: I don't think raw PHP is supported in Blade templates. Use `@php ... @endphp` like above.

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/graphs.blade.php
> +        data: <?php echo json_encode($shipments); ?>,
This is the same problem as with the other raw PHP tags: I don't think raw PHP is supported in Blade templates.

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/layouts/navigation.blade.php
> +              {{ __('Show Shipments') }}
Using named routes is better, so it's best not to change them for normal ones (as they break when the URL changes).

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/layouts/navigation.blade.php
> +                    Auth::user()->roles()->first()->name == 'employee')
Use permissions instead (except for the admin). There is a document in the `/docs/` directory that explains how to use permissions.

2023-04-27 14:22 UTC, ThomasFrans commented on tailwind.config.js
> +// const twPlugin = require('tw-elements/dist/plugin');
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/shipments.blade.php
> +                      {{-- <a href="{{ route('shipments.showShipments_details', $shipment->id) }}"><button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-3
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/shipments.blade.php
> +                    Auth::user()->roles()->first()->name == 'employee')
Use permissions instead.

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/shipments.blade.php
> +                    {{--                                 <a href="{{ route('shipments.showShipments_details', $shipment->id) }}"><button type="button" class="text-white bg-blue-700 hover:bg-blue-800
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/shipments.blade.php
> +              <!-- -->
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

2023-04-27 14:22 UTC, ThomasFrans commented on resources/views/show.blade.php
Remove this file if it isn't used.

2023-04-27 14:22 UTC, ThomasFrans commented on routes/web.php
Restore this file back to how it was and only add your routes. Don't just remove the middleware groups please.

2023-04-27 17:42 UTC, GillesWS commented on package-lock.json
Someone else updated this i think

2023-05-04 07:43 UTC, ThomasFrans commented
Format please

2023-05-20 16:55 UTC, ThomasFrans commented
This contains many mistakes and will break the main branch, including:

- Git merge errors
- Duplicate code

It will have to go into the other main branch and be demonstrated separately, if agreed by @jentevs and @inancalp.

2023-05-21 08:55 UTC, closed without merging