Reviewpage
Practice-Enterprise2/AD pull request #95
Opened 2023-04-26 15:49 UTC by nielsver

2023-04-26 16:17 UTC, ThomasFrans requested changes

2023-04-26 16:17 UTC, ThomasFrans commented on app/Models/review.php
> +class review extends Model
Follow naming conventions

2023-04-26 16:17 UTC, ThomasFrans commented on app/Models/review.php
> +    use HasFactory;
It doesn't have one

2023-04-26 16:17 UTC, ThomasFrans commented on app/Models/review.php
> +    protected $guarded = [];
Don't leave empty `$guarded` (just remove this)

2023-04-26 16:17 UTC, ThomasFrans commented on app/Models/review.php
> +
It's best to add
```php
/**
 * @property int $id
 * @property int $rating
 * @property string $comment
 * @property ?\Illuminate\Support\Carbon $created_at
 * @property ?\Illuminate\Support\Carbon $updated_at
 */
```
before the class for language server support :)

2023-04-26 16:17 UTC, ThomasFrans commented on database/migrations/2023_04_26_124327_create_reviews_table.php
Doesn't a review belong to a user?
Can they be deleted? If so they need soft deletion.

2023-04-27 07:38 UTC, ThomasFrans requested changes
I think you forgot to rename other uses of the Review class, as well as the file (it needs the correct name to be autoincluded I think).

2023-04-27 08:24 UTC, nielsver commented on database/migrations/2023_04_26_124327_create_reviews_table.php
this should belong to a shipment request wich should come from the payment interface. because after the payment interface, you will be redirected to there. so this can't be linked yet because this isn't done yet. i don't see why they should be able to delete those.

2023-04-27 09:49 UTC, ThomasFrans requested changes

2023-04-29 14:04 UTC, closed without merging